"""Executable, versioned metric bindings for the existing source catalog.

Identifiers are generated by trusted source adapters. A physical binding is not
a claim that every operation is valid: unknown meanings remain review_required.
Source units and metadata remain available alongside normalized unit/scale.
"""
from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from typing import Any

import duckdb
import pandas as pd

CONTRACT_VERSION = "1.0.0"
SEMANTIC_POLICY_VERSION = "1.1.1"
FREQUENCIES = {
    "AYLIK": "monthly", "ÜÇ AYLIK": "quarterly", "YILLIK": "yearly",
    "ALTI AYLIK": "half_yearly", "GÜNLÜK": "daily", "İŞ GÜNÜ": "business_daily",
    "HAFTALIK(CUMA)": "weekly_friday", "HAFTALIK(ÇARŞAMBA)": "weekly_wednesday",
    "AYDA İKİ KEZ": "twice_monthly", "weekly": "weekly_friday",
}


def quoted(name: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        raise ValueError(f"Invalid registry identifier: {name}")
    return '"' + name + '"'


def table_sql(name: str) -> str:
    return ".".join(quoted(part) for part in name.split("."))


def rows(connection: duckdb.DuckDBPyConnection, sql: str) -> list[dict[str, Any]]:
    result = connection.execute(sql)
    names = [item[0] for item in result.description]
    return [dict(zip(names, row)) for row in result.fetchall()]


def apply_semantic_policy(binding: dict[str, Any]) -> dict[str, Any]:
    """Apply reviewed source roles without guessing from an index's label.

    The CPI role is documented in the source acquisition manifest
    data_pipeline/evds/manifests/housing_causality_v1.json. Other indices,
    including industrial production and housing prices, are not general CPI
    deflators. Persisted snapshots retain their original binding version/hash;
    the separate policy version identifies these execution-time constraints.
    """
    binding["semantic_policy_version"] = SEMANTIC_POLICY_VERSION
    if binding.get("source_system") == "BDDK_MONTHLY":
        # Monthly source rows lose group_name in their semantic long format.
        # Reuse the monthly acquisition adapter's verified catalog, never the
        # different code meanings in FinTurk or the weekly bulletin.
        from data_pipeline.bddk.build_monthly_all_dataset import GROUPS

        binding["dimension_labels"] = {"group_code": {str(code): label for code, label in GROUPS.items()}}
        binding["dimension_labels_evidence"] = {"group_code": {
            "source": "data_pipeline/bddk/monthly_all_groups/request_config.json#groups",
            "source_url": "https://www.bddk.org.tr/BultenAylik/tr/",
            "verified_at": "2026-09-08", "namespace": "BDDK_MONTHLY"}}
    if binding.get("source_system") == "TCMB_EVDS" and binding.get("source_code") == "TP.TUKFIY2025.GENEL":
        binding.update(index_role="price_deflator", deflator_currency="TRY",
                       price_scope="Turkey general consumer price basket",
                       role_evidence="housing_causality_v1 manifest: price_deflator")
    return binding


def normalized_unit(source_unit: str) -> tuple[str, float, str | None]:
    value = source_unit.strip().casefold().replace("ı", "i")
    units = {
        "milyon tl": ("TRY", 1e6, "TRY"), "million_try": ("TRY", 1e6, "TRY"),
        "bin tl": ("TRY", 1e3, "TRY"), "thousand_try": ("TRY", 1e3, "TRY"),
        "billion_try": ("TRY", 1e9, "TRY"), "billion_usd": ("USD", 1e9, "USD"),
        "tl": ("TRY", 1., "TRY"), "try": ("TRY", 1., "TRY"),
        "adet": ("count", 1., None), "count": ("count", 1., None),
        "person": ("person", 1., None), "kişi": ("person", 1., None),
        "thousand_person": ("person", 1e3, None), "million_person": ("person", 1e6, None),
        "yüzde": ("percent", 1., None), "%": ("percent", 1., None),
        "percent": ("percent", 1., None), "net yüzde değişim": ("percent", 1., None),
        "endeks": ("index", 1., None), "index": ("index", 1., None),
        "day": ("day", 1., None), "gün": ("day", 1., None),
        "tl/m2": ("TRY/m2", 1., "TRY"), "try_per_m2": ("TRY/m2", 1., "TRY"),
        "try_per_person": ("TRY/person", 1., "TRY"),
        "people_per_branch": ("person/branch", 1., None),
        "try_per_gram": ("TRY/gram", 1., "TRY"),
    }
    if value in units:
        return units[value]
    if value.startswith("index_") or re.fullmatch(r"\d{4}=100", value):
        return "index", 1., None
    return source_unit or "unknown", 1., None


def kind_for(semantics: str, unit: str) -> str:
    semantics = semantics.casefold()
    if "flow" in semantics or semantics == "monthly_event_count":
        return "flow"
    if "index" in semantics or unit == "index":
        return "index"
    if semantics in {"count", "count_stock"}:
        return "count_stock"
    if "stock" in semantics:
        return "stock" if unit in {"TRY", "USD"} else "count_stock" if unit in {"count", "person"} else "unknown"
    if "ratio" in semantics or "per_capita" in semantics or semantics in {"monetary_per_entity", "duration", "non_additive_rate"}:
        return "ratio"
    if "rate" in semantics or semantics == "quarterly_survey":
        return "rate"
    if "price" in semantics or "/" in unit:
        return "price"
    if semantics in {"period_end_level", "quarter_end_level", "quarterly_level"} and unit in {"TRY", "USD"}:
        return "stock"
    return "unknown"


def build_bindings(connection: duckdb.DuckDBPyConnection) -> dict[str, dict[str, Any]]:
    tables = {(row[0], row[1]) for row in connection.execute(
        "SELECT table_schema,table_name FROM information_schema.tables").fetchall()}
    # A generic workspace can start with no source catalog. Its explicitly
    # contracted datasets are bound by the service's overlay adapter.
    if ("catalog", "metrics") not in tables:
        return {}
    manifest = rows(connection, "SELECT * FROM catalog.table_manifest") if ("catalog", "table_manifest") in tables else []
    paths: dict[str, list[str]] = {}
    for item in manifest:
        paths.setdefault(item["source_path"], []).append(f"{item['schema_name']}.{item['table_name']}")
    schemas = {(r["table_schema"]+"."+r["table_name"]): {} for r in rows(connection,
        "SELECT table_schema,table_name FROM information_schema.tables")}
    for item in rows(connection, "SELECT table_schema,table_name,column_name,data_type FROM information_schema.columns"):
        schemas.setdefault(item["table_schema"]+"."+item["table_name"], {})[item["column_name"]] = item["data_type"]
    monthly = {r["metric_code"]: r for r in rows(connection, "SELECT * FROM bddk.monthly_metric_dictionary")} if "bddk.monthly_metric_dictionary" in schemas else {}
    definitions: dict[str, list[dict[str, Any]]] = {}
    if "bddk.weekly_metric_versions" in schemas:
        for r in rows(connection, "SELECT * FROM bddk.weekly_metric_versions ORDER BY valid_from"):
            definitions.setdefault(r["metric_code"], []).append({"start":r["valid_from"], "end":r["valid_to"],
                "definition_id":r["definition_id"], "label":r["metric_label"]})
    bindings = {}
    for metric in rows(connection, "SELECT * FROM catalog.metrics ORDER BY metric_id"):
        source, code = metric["source_system"], metric["source_metric_code"]
        candidates = paths.get(metric["source_asset"], [])
        table = candidates[0] if len(candidates) == 1 else None
        unit, scale, currency = normalized_unit(metric["unit"] or "")
        binding = {"metric_id":metric["metric_id"], "title":metric["metric_name_tr"],
            "title_en":metric.get("metric_name_en"), "searchable_text":metric.get("searchable_text"),
            "group_name":metric.get("group_name"), "role":metric.get("role"),
            "source_system":source, "source_code":code, "table":table, "time_column":None,
            "value_column":None, "filters":{}, "dimensions":{},
            "native_frequency":FREQUENCIES.get(metric["native_frequency"], metric["native_frequency"]),
            "kind":kind_for(metric["temporal_semantics"] or "", unit),
            "unit":unit, "source_unit":metric["unit"], "scale":scale, "currency":currency,
            "aggregation":"last", "source_base":"", "provenance_columns":[],
            "status":"metadata_only" if not metric["observation_available"] else "review_required",
            "notes":metric["notes"] or "", "contract_version":CONTRACT_VERSION,
            "coverage_start":metric["coverage_start"], "coverage_end":metric["coverage_end"],
            "observation_count":metric["observation_count"], "missing_observation_count":metric["missing_observation_count"],
            "institution_scope":metric["institution_grain"], "geography_scope":metric["geography_grain"],
            "definition_periods":[], "unit_evidence":"source catalog and explicit source adapter",
            "source_asset":metric["source_asset"], "hash_basis":"file_bytes"}
        apply_semantic_policy(binding)
        if not metric["observation_available"]:
            binding["table"] = None
            bindings[binding["metric_id"]] = binding
            continue
        if source == "BDDK_MONTHLY":
            d = monthly.get(code, {})
            binding.update(time_column="month", value_column="analysis_value", filters={"metric_code":code},
                dimensions={"group_code":"group_code"}, source_base="data_pipeline/bddk/monthly_all_groups",
                provenance_columns=["source_file","source_sha256","source_row_index","value_dimension","source_value","metric_code","group_code","transformation","transformation_status","prior_source_month"],
                institution_scope="BDDK_MONTHLY group namespace", unit_evidence=d.get("unit_evidence", "unreviewed table label"))
            binding.update(source_transformation=d.get("transformation", "identity"),
                           source_semantics=d.get("source_semantics"), analysis_semantics=d.get("analysis_semantics"))
            if d.get("measure_kind"):
                binding["kind"] = kind_for(d["measure_kind"], unit)
            if d.get("denominator_dimension"):
                binding["unit"] += "/"+d["denominator_dimension"]
                binding["kind"] = "ratio"
            binding["notes"] += " " + str(d.get("aggregation_caveat", ""))
            if d.get("semantic_confidence") == "not_applicable":
                binding["kind"] = "unknown"
                binding["blocked_reason"] = "Source structural placeholder, not a usable customer measure."
        elif source == "BDDK_WEEKLY":
            parts = code.split(":")
            metric_code = ":".join(parts[1:3])
            binding.update(table="bddk.weekly_measurements_resolved", time_column="observation_date",
                value_column="value", filters={"metric_code":metric_code,"currency_dimension":parts[-1]},
                dimensions={"group_code":"group_code"}, source_base="data_pipeline/bddk/weekly_all_groups",
                provenance_columns=["source_file","source_sha256","metric_label","definition_id","period_id","table_id","group_code","currency_dimension"],
                institution_scope="BDDK_WEEKLY group namespace", definition_periods=definitions.get(metric_code, []))
            # Native values are discoverable; economic resampling needs an explicit reviewed policy.
            binding["kind"] = "unknown"
            binding["notes"] += " Resampling requires reviewed source semantics; historical definitions cannot be mixed."
        elif source == "BDDK_FINTURK":
            number, measure = code.split(":", 1)
            binding.update(time_column="quarter",value_column="usable_value",filters={"table_no":int(number[5:]),"measure_code":measure},
                dimensions={"group_code":"group_code","city":"city"},source_base="data_pipeline/bddk/finturk_all_groups_all_cities",
                provenance_columns=["source_file","source_sha256","source_row_index","value","value_origin","derivation_formula","measure_code","group_code","city"],
                institution_scope="BDDK_FINTURK group namespace")
        elif source == "TCMB_EVDS":
            binding.update(time_column="period", value_column="value", filters={"series_code":code},
                source_base=metric["source_asset"].rsplit("/",1)[0],
                provenance_columns=["source_response_file","source_response_sha256","source_row_index","series_code","period"],
                hash_basis="decompressed_response")
            if metric["dataset_id"] == "evds.legacy_native":
                binding.update(source_base="", hash_basis="file_bytes",
                    provenance_columns=["source_sha256","vintage","series_code","period"],
                    notes=binding["notes"]+" Source raw locator not present in legacy rows; native artifact and hash retained.")
            semantics = metric["temporal_semantics"] or ""
            if "index" in semantics:
                binding.update(unit="index",kind="index",currency=None,scale=1.)
            explicit = {
                "TP.KTF12":("percent",1.,None,"rate"), "TP.BKR.TRY.18":("percent",1.,None,"rate"),
                "TP.APIFON4":("percent",1.,None,"rate"), "TP.TIG08":("percent",1.,None,"rate"),
                "TP.ALTINPIYASA.KAP02":("TRY/kg",1.,"TRY","price"),
                "TP.ALTINPIYASA.KAP05":("TRY/gram",1.,"TRY","price"),
                "TP.KKM.K1":("TRY",1e9,"TRY","stock"),
                "TP.KKM.K2":("USD",1e9,"USD","stock"),
                "TP.KKM.K4":("USD",1e9,"USD","stock"),
            }
            if code in explicit:
                binding["unit"],binding["scale"],binding["currency"],binding["kind"] = explicit[code]
                binding["unit_evidence"] = "Reviewed source-series meaning; group-level unit is not authoritative."
            method = metric["default_aggregation"]
            binding["aggregation"] = method if method in {"sum","last","mean"} else "last"
            if code == "TP.KTF12":
                binding["notes"] += " Monthly mean is the unweighted mean of published weekly rates, not a loan-volume-weighted monthly rate."
        elif source == "TCMB_EVDS_DERIVED":
            binding.update(time_column="target_period",value_column=code.replace(".","_").replace("-","_"),
                native_frequency="monthly",kind="price",unit="TRY/gram",currency="TRY",scale=1.,
                provenance_columns=[],derivation={"source_metric_id":"evds:TP.ALTINPIYASA.KAP02", "operation":"scale", "factor":0.001},
                notes=binding["notes"]+" Derived monthly value; inspect alignment audit for chosen native date.",
                blocked_reason="Derived source-cell lineage must be resolved before further numerical transformations.")
        elif source == "TBB_REPORTS":
            measure, product, group = code.split(":")
            source_group = {"TRY":"TP","FX-linked":"YP","Total":"Toplam"}[group]
            binding.update(time_column="quarter",value_column=product,
                filters={"measure":measure,"source_currency_group":source_group},
                source_base="data_pipeline/tbb",provenance_columns=["source_file","source_sha256","source_row_index","source_currency_group","measure","report_period"],
                notes=binding["notes"]+" YP means foreign-currency loans reported in TRY, not necessarily FX-linked loans. Person counts are not deduplicated across banks or products.")
            if "person_count" in measure:
                binding.update(unit="person",scale=1.,currency=None,
                    kind="flow" if measure.startswith("disbursement") else "count_stock")
        elif source == "TBB_RISK_CENTER":
            binding.update(table="risk_center.housing_metrics_latest",time_column="observation_month",value_column="value",
                filters={"metric_code":code},source_base="",provenance_columns=["source_file","source_sha256","source_page_number","publication_month","source_display_precision","source_value_raw"],
                notes=binding["notes"]+" Publication-month label is source vintage, not verified actual release date.")
        elif source == "TUIK_DATA_PORTAL":
            binding.update(time_column="month",value_column="value",filters={"metric_code":code},dimensions={"province_key":"province_key"},
                source_base="",provenance_columns=["source_csv_file","source_csv_sha256","value_origin","derivation","province_key","metric_code"],
                hash_basis="decompressed_response")
        elif source == "REGIONAL_HOUSING_ANALYSIS":
            binding.update(time_column="quarter",value_column=code,dimensions={"province_key":"province_key"},
                provenance_columns=[],notes=binding["notes"]+" Derived panel. Query-specific missingness applies; source/proxy lineage differs by column.",
                blocked_reason="Derived panel recipe not yet mapped to individual source cells; use source-native binding for transformations.")
            if "proxy" in code:
                binding["blocked_reason"] = "Proxy requires explicit reviewed policy; use official source metric by default."
        available = schemas.get(binding["table"], {})
        binding["dimension_label_columns"] = {"group_code": "group_name"} if "group_code" in binding["dimensions"] and "group_name" in available else {}
        identifiers = [binding["time_column"],binding["value_column"],*binding["filters"],*binding["dimensions"].values()]
        binding["binding_available"] = bool(available) and all(name in available for name in identifiers)
        binding["provenance_columns"] = [name for name in binding["provenance_columns"] if name in available]
        if binding["binding_available"]:
            dtype = available[binding["value_column"]]
            numeric = dtype.startswith(("DOUBLE","FLOAT","BIGINT","INTEGER","DECIMAL","SMALLINT"))
            binding["physical_grain"] = [binding["time_column"],*binding["filters"],*binding["dimensions"].values()]
            binding["dimension_types"] = {key:available[col] for key,col in binding["dimensions"].items()}
            if not numeric:
                binding["blocked_reason"] = "Categorical field: numerical operations are not available."
            known_unit = binding["unit"] in {"TRY","USD","count","person","percent","index","day","TRY/m2","TRY/gram","TRY/kg","TRY/person","TRY/branch","person/branch"}
            if numeric and known_unit and binding["kind"] != "unknown" and not binding.get("blocked_reason"):
                binding["status"] = "ready"
            if metric["observation_count"] <= metric["missing_observation_count"]:
                binding["status"] = "no_numeric"
        else:
            binding["blocked_reason"] = "No unambiguous executable observation binding."
        if binding["kind"] == "flow":
            binding["aggregation"] = "sum"
        binding["binding_sha256"] = hashlib.sha256(json.dumps(binding,sort_keys=True,ensure_ascii=False,default=str).encode()).hexdigest()
        bindings[binding["metric_id"]] = binding
    return bindings


def install_bindings(connection: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    bindings = build_bindings(connection)
    frame = pd.DataFrame([{"metric_id":key,"status":item["status"],"contract_version":CONTRACT_VERSION,
                           "binding_json":(None if item["status"] == "metadata_only" else
                               json.dumps(item,ensure_ascii=False,sort_keys=True,allow_nan=False))}
                          for key,item in bindings.items()], columns=["metric_id", "status", "contract_version", "binding_json"])
    if frame.empty:
        frame = frame.astype({name: "string" for name in frame.columns})
    connection.execute("CREATE SCHEMA IF NOT EXISTS catalog")
    connection.register("_metric_bindings",frame)
    try:
        connection.execute("CREATE TABLE catalog.metric_bindings AS SELECT * FROM _metric_bindings")
    finally:
        connection.unregister("_metric_bindings")
    return {"count":len(bindings),"status_counts":dict(Counter(b["status"] for b in bindings.values())),
            "contract_version":CONTRACT_VERSION}


def get_bindings(connection: duckdb.DuckDBPyConnection) -> dict[str, dict[str, Any]]:
    """Read persisted contracts, keeping queries on the same pinned snapshot."""
    exists = connection.execute("SELECT count(*) FROM information_schema.tables WHERE table_schema='catalog' AND table_name='metric_bindings'").fetchone()[0]
    if not exists:
        catalog_exists = connection.execute("SELECT count(*) FROM information_schema.tables WHERE table_schema='catalog' AND table_name='metrics'").fetchone()[0]
        if not catalog_exists:
            return {}
        raise ValueError("Metric contracts are absent. Rebuild the lakehouse before serving agent queries.")
    payload_rows = connection.execute("SELECT metric_id,binding_json FROM catalog.metric_bindings").fetchall()
    result = {row[0]:apply_semantic_policy(json.loads(row[1])) for row in payload_rows if row[1] is not None}
    catalog_columns = {row[0] for row in connection.execute("SELECT column_name FROM information_schema.columns WHERE table_schema='catalog' AND table_name='metrics'").fetchall()}
    searchable = [name for name in ("metric_name_en", "searchable_text", "group_name", "role") if name in catalog_columns]
    if searchable:
        for metric in rows(connection, "SELECT m.metric_id," + ",".join("m." + name for name in searchable) + " FROM catalog.metrics m JOIN catalog.metric_bindings b USING(metric_id) WHERE b.binding_json IS NOT NULL"):
            binding = result[metric["metric_id"]]
            binding.update({"title_en" if key == "metric_name_en" else key: value for key, value in metric.items() if key != "metric_id"})
    table_columns: dict[str, set[str]] = {}
    for row in connection.execute("SELECT table_schema,table_name,column_name FROM information_schema.columns").fetchall():
        table_columns.setdefault(row[0] + "." + row[1], set()).add(row[2])
    for binding in result.values():
        if "group_code" in binding.get("dimensions", {}) and "group_name" in table_columns.get(binding.get("table"), set()):
            binding["dimension_label_columns"] = {"group_code": "group_name"}
    if all(row[1] is not None for row in payload_rows):
        return result
    # Metadata-only series have no physical binding. Reuse the existing catalog
    # instead of persisting another 52k copies of their descriptions and units.
    for metric in rows(connection, """SELECT m.* FROM catalog.metrics m JOIN catalog.metric_bindings b
            USING(metric_id) WHERE b.binding_json IS NULL"""):
        unit,scale,currency = normalized_unit(metric["unit"] or "")
        result[metric["metric_id"]] = {"metric_id":metric["metric_id"], "title":metric["metric_name_tr"],
            "title_en":metric.get("metric_name_en"), "searchable_text":metric.get("searchable_text"), "group_name":metric.get("group_name"),
            "source_system":metric["source_system"], "source_code":metric["source_metric_code"],
            "table":None,"time_column":None,"value_column":None,"filters":{},"dimensions":{},
            "native_frequency":FREQUENCIES.get(metric["native_frequency"],metric["native_frequency"]),
            "kind":"unknown","unit":unit,"scale":scale,"currency":currency,
            "status":"metadata_only","notes":metric["notes"],"contract_version":CONTRACT_VERSION,
            "coverage_start":metric["coverage_start"],"coverage_end":metric["coverage_end"],
            "observation_count":metric["observation_count"],"source_asset":metric["source_asset"],
            "binding_available":False,"blocked_reason":"Observation data not ingested."}
    return result
