"""Executable, versioned metric bindings for the existing source catalog.

Identifiers are generated by trusted source adapters. A physical binding is not
a claim that every operation is valid: unknown meanings remain review_required.
Source units and metadata remain available alongside normalized unit/scale.
"""
from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from typing import Any

import duckdb
import pandas as pd

from agentic_analytics.lakehouse.semantics import (
    CONTRACT_VERSION, FREQUENCIES, apply_semantic_policy, kind_for, normalized_unit,
)
from agentic_analytics.lakehouse.source_profiles import apply_source_profile

def quoted(name: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        raise ValueError(f"Invalid registry identifier: {name}")
    return '"' + name + '"'


def table_sql(name: str) -> str:
    return ".".join(quoted(part) for part in name.split("."))


def rows(connection: duckdb.DuckDBPyConnection, sql: str) -> list[dict[str, Any]]:
    result = connection.execute(sql)
    names = [item[0] for item in result.description]
    return [dict(zip(names, row)) for row in result.fetchall()]


def build_bindings(connection: duckdb.DuckDBPyConnection) -> dict[str, dict[str, Any]]:
    tables = {(row[0], row[1]) for row in connection.execute(
        "SELECT table_schema,table_name FROM information_schema.tables").fetchall()}
    # A generic workspace can start with no source catalog. Its explicitly
    # contracted datasets are bound by the service's overlay adapter.
    if ("catalog", "metrics") not in tables:
        return {}
    manifest = rows(connection, "SELECT * FROM catalog.table_manifest") if ("catalog", "table_manifest") in tables else []
    paths: dict[str, list[str]] = {}
    for item in manifest:
        paths.setdefault(item["source_path"], []).append(f"{item['schema_name']}.{item['table_name']}")
    schemas = {(r["table_schema"]+"."+r["table_name"]): {} for r in rows(connection,
        "SELECT table_schema,table_name FROM information_schema.tables")}
    for item in rows(connection, "SELECT table_schema,table_name,column_name,data_type FROM information_schema.columns"):
        schemas.setdefault(item["table_schema"]+"."+item["table_name"], {})[item["column_name"]] = item["data_type"]
    monthly = {r["metric_code"]: r for r in rows(connection, "SELECT * FROM bddk.monthly_metric_dictionary")} if "bddk.monthly_metric_dictionary" in schemas else {}
    definitions: dict[str, list[dict[str, Any]]] = {}
    if "bddk.weekly_metric_versions" in schemas:
        for r in rows(connection, "SELECT * FROM bddk.weekly_metric_versions ORDER BY valid_from"):
            definitions.setdefault(r["metric_code"], []).append({"start":r["valid_from"], "end":r["valid_to"],
                "definition_id":r["definition_id"], "label":r["metric_label"]})
    bindings = {}
    for metric in rows(connection, "SELECT * FROM catalog.metrics ORDER BY metric_id"):
        source, code = metric["source_system"], metric["source_metric_code"]
        candidates = paths.get(metric["source_asset"], [])
        table = candidates[0] if len(candidates) == 1 else None
        unit, scale, currency = normalized_unit(metric["unit"] or "")
        binding = {"metric_id":metric["metric_id"], "dataset_id":metric["dataset_id"], "title":metric["metric_name_tr"],
            "title_en":metric.get("metric_name_en"), "searchable_text":metric.get("searchable_text"),
            "group_name":metric.get("group_name"), "role":metric.get("role"),
            "source_organization":metric.get("source_organization"),
            "competition_scope":metric.get("competition_scope"),
            "vintage_policy":metric.get("vintage_policy"), "release_date":metric.get("release_date"),
            "revision_status":metric.get("revision_status"),
            "canonical_series_code":metric.get("canonical_series_code"),
            "historical_name":metric.get("historical_name"),
            "current_name":metric.get("current_name"),
            "name_change_effective_date":metric.get("name_change_effective_date"),
            "name_change_source_url":metric.get("name_change_source_url"),
            "scale_revision_effective_date":metric.get("scale_revision_effective_date"),
            "scale_revision_factor":metric.get("scale_revision_factor"),
            "scale_revision_source_url":metric.get("scale_revision_source_url"),
            "historical_archive_source_url":metric.get("historical_archive_source_url"),
            "historical_original_scale_included":metric.get("historical_original_scale_included"),
            "methodology_source_url":metric.get("methodology_source_url"),
            "official_series_url":metric.get("official_series_url"),
            "source_metadata_url":metric.get("source_metadata_url"),
            "source_url":metric.get("source_metadata_url"),
            "source_system":source, "scope_namespace":source, "source_code":code, "table":table, "time_column":None,
            "value_column":None, "filters":{}, "dimensions":{},
            "native_frequency":FREQUENCIES.get(metric["native_frequency"], metric["native_frequency"]),
            "kind":kind_for(metric["temporal_semantics"] or "", unit),
            "unit":unit, "source_unit":metric["unit"], "scale":scale, "currency":currency,
            "aggregation":"last", "source_base":"", "provenance_columns":[],
            "status":"metadata_only" if not metric["observation_available"] else "review_required",
            "notes":metric["notes"] or "", "contract_version":CONTRACT_VERSION,
            "coverage_start":metric["coverage_start"], "coverage_end":metric["coverage_end"],
            "observation_count":metric["observation_count"], "missing_observation_count":metric["missing_observation_count"],
            "institution_scope":metric["institution_grain"], "geography_scope":metric["geography_grain"],
            "definition_periods":[], "unit_evidence":"source catalog and explicit source adapter",
            "source_asset":metric["source_asset"], "hash_basis":"file_bytes"}
        apply_semantic_policy(binding)
        if not metric["observation_available"]:
            binding["table"] = None
            bindings[binding["metric_id"]] = binding
            continue
        if source == "BDDK_MONTHLY":
            d = monthly.get(code, {})
            binding.update(time_column="month", value_column="analysis_value", filters={"metric_code":code},
                dimensions={"group_code":"group_code"}, source_base="data_pipeline/bddk/monthly_all_groups",
                provenance_columns=["source_file","source_sha256","source_row_index","value_dimension","source_value","metric_code","group_code","transformation","transformation_status","prior_source_month"],
                institution_scope="BDDK_MONTHLY group namespace", unit_evidence=d.get("unit_evidence", "unreviewed table label"))
            binding.update(source_transformation=d.get("transformation", "identity"),
                           source_semantics=d.get("source_semantics"), analysis_semantics=d.get("analysis_semantics"))
            if d.get("measure_kind"):
                binding["kind"] = kind_for(d["measure_kind"], unit)
            if d.get("denominator_dimension"):
                binding["unit"] += "/"+d["denominator_dimension"]
                binding["kind"] = "ratio"
            binding["notes"] += " " + str(d.get("aggregation_caveat", ""))
            if d.get("semantic_confidence") == "not_applicable":
                binding["kind"] = "unknown"
                binding["blocked_reason"] = "Source structural placeholder, not a usable customer measure."
        elif source == "BDDK_WEEKLY":
            parts = code.split(":")
            metric_code = ":".join(parts[1:3])
            binding.update(table="bddk.weekly_measurements_resolved", time_column="observation_date",
                value_column="value", filters={"metric_code":metric_code,"currency_dimension":parts[-1]},
                dimensions={"group_code":"group_code"}, source_base="data_pipeline/bddk/weekly_all_groups",
                provenance_columns=["source_file","source_sha256","metric_label","definition_id","period_id","table_id","group_code","currency_dimension"],
                institution_scope="BDDK_WEEKLY group namespace", definition_periods=definitions.get(metric_code, []))
            if not code.startswith("table289:"):
                # Other weekly tables remain discoverable at native grain, but
                # their economic resampling policy has not been reviewed.
                binding["kind"] = "unknown"
                binding["notes"] += " Resampling requires reviewed source semantics; historical definitions cannot be mixed."
            else:
                binding["notes"] += " Actual BDDK observation dates are retained, including holiday-shifted weekly issues; historical definitions cannot be mixed."
        elif source == "BDDK_FINTURK":
            number, measure = code.split(":", 1)
            binding.update(time_column="quarter",value_column="usable_value",filters={"table_no":int(number[5:]),"measure_code":measure},
                dimensions={"group_code":"group_code","city":"city"},source_base="data_pipeline/bddk/finturk_all_groups_all_cities",
                provenance_columns=["source_file","source_sha256","source_row_index","value","value_origin","derivation_formula","measure_code","group_code","city"],
                institution_scope="BDDK_FINTURK group namespace")
        elif source == "TCMB_EVDS":
            binding.update(time_column="period", value_column="value", filters={"series_code":code},
                source_base=metric["source_asset"].rsplit("/",1)[0],
                provenance_columns=["source_response_file","source_response_sha256","source_row_index","series_code","period"],
                hash_basis="decompressed_response")
            if metric["dataset_id"] == "evds.full_catalog":
                binding.update(kind="unknown", aggregation="review_required",
                    provenance_columns=["source_response_file", "source_response_sha256", "source_request_file",
                        "source_request_sha256", "source_row_index", "source_cell_path", "source_job_id", "source_attempt", "series_code",
                        "period", "source_date_label", "value_raw", "is_missing", "missing_kind", "is_unresolved_missing"],
                    unit_evidence="EVDS native metadata unit retained; group-level labels and economic kind require review.")
            if metric["dataset_id"] == "evds.legacy_native":
                binding.update(source_base="", hash_basis="file_bytes",
                    provenance_columns=["source_sha256","vintage","series_code","period"],
                    notes=binding["notes"]+" Source raw locator not present in legacy rows; native artifact and hash retained.")
            semantics = metric["temporal_semantics"] or ""
            if "index" in semantics:
                binding.update(unit="index",kind="index",currency=None,scale=1.)
            explicit = {
                "TP.KTF12":("percent",1.,None,"rate"), "TP.BKR.TRY.18":("percent",1.,None,"rate"),
                "TP.APIFON4":("percent",1.,None,"rate"), "TP.TIG08":("percent",1.,None,"rate"),
                "TP.BKR.TRY.17":("percent",1.,None,"rate"), "TP.BKR.TRY.1":("percent",1.,None,"rate"),
                "TP.TRY.MT02":("percent",1.,None,"rate"),
                "TP.ALTINPIYASA.KAP02":("TRY/kg",1.,"TRY","price"),
                "TP.ALTINPIYASA.KAP05":("TRY/gram",1.,"TRY","price"),
                "TP.KKM.K1":("TRY",1e9,"TRY","stock"),
                "TP.KKM.K2":("USD",1e9,"USD","stock"),
                "TP.KKM.K4":("USD",1e9,"USD","stock"),
            }
            if code in explicit and metric["dataset_id"] != "evds.full_catalog":
                binding["unit"],binding["scale"],binding["currency"],binding["kind"] = explicit[code]
                binding["unit_evidence"] = "Reviewed source-series meaning; group-level unit is not authoritative."
            method = metric["default_aggregation"]
            binding["aggregation"] = ("review_required" if metric["dataset_id"] == "evds.full_catalog"
                                      else method if method in {"sum","last","mean"} else "last")
            if code == "TP.KTF12":
                binding["notes"] += " Monthly mean is the unweighted mean of published weekly rates, not a loan-volume-weighted monthly rate."
        elif source == "TCMB_EVDS_DERIVED":
            binding.update(time_column="target_period",value_column=code.replace(".","_").replace("-","_"),
                native_frequency="monthly",kind="price",unit="TRY/gram",currency="TRY",scale=1.,
                provenance_columns=[],derivation={"source_metric_id":"evds:TP.ALTINPIYASA.KAP02", "operation":"scale", "factor":0.001},
                notes=binding["notes"]+" Derived monthly value; inspect alignment audit for chosen native date.",
                blocked_reason="Derived source-cell lineage must be resolved before further numerical transformations.")
        elif source == "TBB_REPORTS":
            measure, product, group = code.split(":")
            source_group = {"TRY":"TP","FX-linked":"YP","Total":"Toplam"}[group]
            binding.update(time_column="quarter",value_column=product,
                filters={"measure":measure,"source_currency_group":source_group},
                source_base="data_pipeline/tbb",provenance_columns=["source_file","source_sha256","source_row_index","source_currency_group","measure","report_period"],
                notes=binding["notes"]+" YP means foreign-currency loans reported in TRY, not necessarily FX-linked loans. Person counts are not deduplicated across banks or products.")
            if "person_count" in measure:
                binding.update(unit="person",scale=1.,currency=None,
                    kind="flow" if measure.startswith("disbursement") else "count_stock")
        elif source == "TBB_RISK_CENTER":
            binding.update(table="risk_center.housing_metrics_latest",time_column="observation_month",value_column="value",
                filters={"metric_code":code},source_base="",provenance_columns=["source_file","source_sha256","source_page_number","publication_month","source_display_precision","source_value_raw"],
                notes=binding["notes"]+" Publication-month label is source vintage, not verified actual release date.")
        elif source == "TUIK_DATA_PORTAL":
            binding.update(time_column="month",value_column="value",filters={"metric_code":code},dimensions={"province_key":"province_key"},
                source_base="",provenance_columns=["source_csv_file","source_csv_sha256","source_file","source_sha256",
                    "source_row_index","source_column_index","source_cell","source_sheet","source_press_id","source_press_title",
                    "source_press_period","source_press_url","source_press_api_url","source_download_url","release_at",
                    "source_vintage_at","revision_status","vintage_policy","methodology_revision_date",
                    "methodology_revision_press_id","methodology_revision_url","value_origin","derivation","province_key","metric_code"],
                hash_basis="decompressed_response")
            binding["scope_namespace"] = metric["dataset_id"]
            if metric["dataset_id"] == "tuik.province_housing_sales_first_published_v1":
                binding["measurement_basis"] = "tuik_housing_definition_pre_2026_first_publication"
                binding["methodology_revision_date"] = "2026-02-19"
                binding["notes"] += " This is the first official bulletin vintage, not the current revised series."
                binding.setdefault("scope_caveats", []).append({
                    "code": "historical_first_publication_vintage",
                    "source_url": "https://veriportali.tuik.gov.tr/tr/press/58340",
                    "message": "TÜİK revised housing-sale history from 2013 in 2026. Keep this first-published bulletin series separate from the current revised bulk series.",
                })
            else:
                binding["measurement_basis"] = "tuik_housing_definition_revised_2026"
                binding["methodology_revision_date"] = "2026-02-19"
                binding["notes"] += " This is the current official bulk vintage after the 2026 methodology revision."
                binding.setdefault("scope_caveats", []).append({
                    "code": "current_revised_vintage",
                    "source_url": "https://veriportali.tuik.gov.tr/tr/press/58340",
                    "message": "Historical values use TÜİK's 2026 revised housing definition and can differ from contemporaneous first publications.",
                })
        elif source == "REGIONAL_HOUSING_ANALYSIS":
            binding.update(time_column="quarter",value_column=code,dimensions={"province_key":"province_key"},
                provenance_columns=[],notes=binding["notes"]+" Derived panel. Query-specific missingness applies; source/proxy lineage differs by column.",
                blocked_reason="Derived panel recipe not yet mapped to individual source cells; use source-native binding for transformations.")
            if "proxy" in code:
                binding["blocked_reason"] = "Proxy requires explicit reviewed policy; use official source metric by default."
        available = schemas.get(binding["table"], {})
        binding["dimension_label_columns"] = {"group_code": "group_name"} if "group_code" in binding["dimensions"] and "group_name" in available else {}
        identifiers = [binding["time_column"],binding["value_column"],*binding["filters"],*binding["dimensions"].values()]
        binding["binding_available"] = bool(available) and all(name in available for name in identifiers)
        binding["provenance_columns"] = [name for name in binding["provenance_columns"] if name in available]
        if metric["dataset_id"] == "evds.full_catalog" and "source_cell_path" in binding["provenance_columns"]:
            binding["source_cell_locator_policy"] = {
                "value_location": "source_cell_path is authoritative when present",
                "path_format": "JSON Pointer with zero-based array indices",
                "source_row_index_role": "one-based items date-row anchor; does not identify the value container",
            }
        if binding["binding_available"]:
            dtype = available[binding["value_column"]]
            numeric = dtype.startswith(("DOUBLE","FLOAT","BIGINT","INTEGER","DECIMAL","SMALLINT"))
            binding["physical_grain"] = [binding["time_column"],*binding["filters"],*binding["dimensions"].values()]
            binding["dimension_types"] = {key:available[col] for key,col in binding["dimensions"].items()}
            if not numeric:
                binding["blocked_reason"] = "Categorical field: numerical operations are not available."
            known_unit = binding["unit"] in {"TRY","USD","count","person","percent","index","day","TRY/m2","TRY/gram","TRY/kg","TRY/person","TRY/branch","person/branch"}
            if numeric and known_unit and binding["kind"] != "unknown" and not binding.get("blocked_reason"):
                binding["status"] = "ready"
            if metric["observation_count"] <= metric["missing_observation_count"]:
                binding["status"] = "no_numeric"
        else:
            binding["blocked_reason"] = "No unambiguous executable observation binding."
        if binding["kind"] == "flow":
            binding["aggregation"] = "sum"
        apply_source_profile(binding)
        binding["binding_sha256"] = hashlib.sha256(json.dumps(binding,sort_keys=True,ensure_ascii=False,default=str).encode()).hexdigest()
        bindings[binding["metric_id"]] = binding
    return bindings


def install_bindings(connection: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    bindings = build_bindings(connection)
    frame = pd.DataFrame([{"metric_id":key,"status":item["status"],"contract_version":CONTRACT_VERSION,
                           "binding_json":(None if item["status"] == "metadata_only" else
                               json.dumps(item,ensure_ascii=False,sort_keys=True,allow_nan=False))}
                          for key,item in bindings.items()], columns=["metric_id", "status", "contract_version", "binding_json"])
    if frame.empty:
        frame = frame.astype({name: "string" for name in frame.columns})
    connection.execute("CREATE SCHEMA IF NOT EXISTS catalog")
    connection.register("_metric_bindings",frame)
    try:
        connection.execute("CREATE TABLE catalog.metric_bindings AS SELECT * FROM _metric_bindings")
    finally:
        connection.unregister("_metric_bindings")
    return {"count":len(bindings),"status_counts":dict(Counter(b["status"] for b in bindings.values())),
            "contract_version":CONTRACT_VERSION}


def get_bindings(connection: duckdb.DuckDBPyConnection) -> dict[str, dict[str, Any]]:
    """Read persisted contracts, keeping queries on the same pinned snapshot."""
    exists = connection.execute("SELECT count(*) FROM information_schema.tables WHERE table_schema='catalog' AND table_name='metric_bindings'").fetchone()[0]
    if not exists:
        catalog_exists = connection.execute("SELECT count(*) FROM information_schema.tables WHERE table_schema='catalog' AND table_name='metrics'").fetchone()[0]
        if not catalog_exists:
            return {}
        raise ValueError("Metric contracts are absent. Rebuild the lakehouse before serving agent queries.")
    payload_rows = connection.execute("SELECT metric_id,binding_json FROM catalog.metric_bindings").fetchall()
    result = {row[0]:apply_semantic_policy(json.loads(row[1])) for row in payload_rows if row[1] is not None}
    catalog_columns = {row[0] for row in connection.execute("SELECT column_name FROM information_schema.columns WHERE table_schema='catalog' AND table_name='metrics'").fetchall()}
    # Propagate the structural disambiguator columns the catalog already computes
    # (slice token, archive flag, temporal semantics, curation) so discover/describe
    # can distinguish a canonical metric from its near-identical decoy siblings.
    searchable = [name for name in ("metric_name_en", "searchable_text", "group_name", "role",
                                    "source_organization", "competition_scope",
                                    "dimension", "is_archive", "temporal_semantics", "quality_status")
                  if name in catalog_columns]
    if searchable:
        for metric in rows(connection, "SELECT m.metric_id," + ",".join("m." + name for name in searchable) + " FROM catalog.metrics m JOIN catalog.metric_bindings b USING(metric_id) WHERE b.binding_json IS NOT NULL"):
            binding = result[metric["metric_id"]]
            binding.update({("title_en" if key == "metric_name_en" else "value_dimension" if key == "dimension" else key): value
                            for key, value in metric.items() if key != "metric_id"})
    table_columns: dict[str, set[str]] = {}
    for row in connection.execute("SELECT table_schema,table_name,column_name FROM information_schema.columns").fetchall():
        table_columns.setdefault(row[0] + "." + row[1], set()).add(row[2])
    for binding in result.values():
        apply_source_profile(binding)
        if "group_code" in binding.get("dimensions", {}) and "group_name" in table_columns.get(binding.get("table"), set()):
            binding["dimension_label_columns"] = {"group_code": "group_name"}
    if all(row[1] is not None for row in payload_rows):
        return result
    # Metadata-only series have no physical binding. Reuse the existing catalog
    # instead of persisting another 52k copies of their descriptions and units.
    for metric in rows(connection, """SELECT m.* FROM catalog.metrics m JOIN catalog.metric_bindings b
            USING(metric_id) WHERE b.binding_json IS NULL"""):
        unit,scale,currency = normalized_unit(metric["unit"] or "")
        result[metric["metric_id"]] = {"metric_id":metric["metric_id"], "dataset_id":metric["dataset_id"], "title":metric["metric_name_tr"],
            "title_en":metric.get("metric_name_en"), "searchable_text":metric.get("searchable_text"), "group_name":metric.get("group_name"),
            "canonical_series_code":metric.get("canonical_series_code"), "historical_name":metric.get("historical_name"),
            "current_name":metric.get("current_name"), "name_change_effective_date":metric.get("name_change_effective_date"),
            "name_change_source_url":metric.get("name_change_source_url"),
            "scale_revision_effective_date":metric.get("scale_revision_effective_date"),
            "scale_revision_factor":metric.get("scale_revision_factor"),
            "scale_revision_source_url":metric.get("scale_revision_source_url"),
            "historical_archive_source_url":metric.get("historical_archive_source_url"),
            "historical_original_scale_included":metric.get("historical_original_scale_included"),
            "methodology_source_url":metric.get("methodology_source_url"),
            "official_series_url":metric.get("official_series_url"),
            "source_metadata_url":metric.get("source_metadata_url"), "source_url":metric.get("source_metadata_url"),
            "source_system":metric["source_system"], "source_organization":metric.get("source_organization"),
            "competition_scope":metric.get("competition_scope"),
            "scope_namespace":metric["source_system"], "source_code":metric["source_metric_code"],
            "table":None,"time_column":None,"value_column":None,"filters":{},"dimensions":{},
            "native_frequency":FREQUENCIES.get(metric["native_frequency"],metric["native_frequency"]),
            "kind":"unknown","unit":unit,"scale":scale,"currency":currency,
            "status":"metadata_only","notes":metric["notes"],"contract_version":CONTRACT_VERSION,
            "coverage_start":metric["coverage_start"],"coverage_end":metric["coverage_end"],
            "observation_count":metric["observation_count"],"source_asset":metric["source_asset"],
            "binding_available":False,"blocked_reason":"Observation data not ingested."}
    return result
